# This file is auto-generated by translations_codegen.py

translations_tuple = [
    (
        ("*", "Active Character ID"),
        (("",), ""),
        ("zh_HANS", "选中角色 ID", (False, ())),
    ),
    (
        ("Operator", "Add Outline to Selected"),
        (("bpy.types.SSSEKAI_OT_apply_outline_op",), ""),
        ("zh_HANS", "添加描边", (False, ())),
    ),
    (
        ("*", "Add outline to selected objects"),
        (("bpy.types.SSSEKAI_OT_apply_outline_op",), ""),
        ("zh_HANS", "向选中对象添加描边", (False, ())),
    ),
    (
        ("*", "Animation Offset in frames"),
        (("",), ""),
        ("zh_HANS", "动画偏移帧数", (False, ())),
    ),
    (
        ("*", "Animation Options"),
        (("scripts/addons/sssekai_blender_io/blender/addon.py:936",), ""),
        ("zh_HANS", "动画选项", (False, ())),
    ),
    (
        ("*", "Append"),
        ((("scripts/addons/sssekai_blender_io/blender/addon.py:1070",),), ""),
        ("zh_HANS", "追加", (False, ())),
    ),
    (
        ("*", "Append Animations to the existing Action, instead of overwriting it"),
        (("",), ""),
        ("zh_HANS", "将动画附加到现有动作中，而不是覆盖它", (False, ())),
    ),
    (
        ("Operator", "Apply Modifiers"),
        (("bpy.types.SSSEKAI_OT_util_apply_modifiers_op",), ""),
        ("zh_HANS", "应用修改器", (False, ())),
    ),
    (
        (
            "*",
            "Apply all modifiers to the selected objects's meshes. Snippet from "
            "github.com/przemir/ApplyModifierForObjectWithShapeKeys",
        ),
        (("bpy.types.SSSEKAI_OT_util_apply_modifiers_op",), ""),
        (
            "zh_HANS",
            "将所有修改器应用到选中对象的网格上。Ref: "
            "github.com/przemir/ApplyModifierForObjectWithShapeKeys",
            (False, ()),
        ),
    ),
    (
        ("*", "Armature"),
        (("scripts/addons/sssekai_blender_io/blender/addon.py:271",), ""),
        ("zh_HANS", "骨架", (False, ())),
    ),
    (
        ("*", "Armature Options"),
        (("scripts/addons/sssekai_blender_io/blender/addon.py:928",), ""),
        ("zh_HANS", "骨架选项", (False, ())),
    ),
    (
        ("*", "Armatures as Articulations"),
        (("",), ""),
        ("zh_HANS", "关节形式导入骨架", (False, ())),
    ),
    (
        ("*", "Asset"),
        ((("scripts/addons/sssekai_blender_io/blender/addon.py:1029",),), ""),
        ("zh_HANS", "素材", (False, ())),
    ),
    (
        ("Operator", "Attach"),
        (("bpy.types.SSSEKAI_OT_util_neck_attach_op",), ""),
        ("zh_HANS", "连接", (False, ())),
    ),
    (
        ("*", "Attach Neck"),
        (("bpy.types.OBJ_PT_sssekai_util_neck_attach",), ""),
        ("zh_HANS", "连接颈部", (False, ())),
    ),
    (
        ("*", "Attach the selected face armature to the selected body armature"),
        (("bpy.types.SSSEKAI_OT_util_neck_attach_op",), ""),
        ("zh_HANS", "将选中的面部骨架连接到选中的身体骨架", (False, ())),
    ),
    (("*", "Body"), (("",), ""), ("zh_HANS", "身体", (False, ()))),
    (("*", "Character ID"), (("",), ""), ("zh_HANS", "角色 ID", (False, ()))),
    (
        ("*", "Character IDs: %s"),
        (("",), ""),
        ("zh_HANS", "有效角色 ID：%s", (False, ())),
    ),
    (
        ("*", "Character IDs: %s,"),
        (("scripts/addons/sssekai_blender_io/blender/addon.py:886",), ""),
        ("zh_HANS", "角色 ID：%s,", (False, ())),
    ),
    (
        ("*", "Directory"),
        ((("scripts/addons/sssekai_blender_io/blender/addon.py:1024",),), ""),
        ("zh_HANS", "文件夹", (False, ())),
    ),
    (("*", "Display Physics"), (("",), ""), ("zh_HANS", "显示物理", (False, ()))),
    (
        ("*", "Display Physics Objects"),
        (("",), ""),
        ("zh_HANS", "显示物理物体", (False, ())),
    ),
    (
        ("Operator", "Export Animation TypeTree"),
        (("bpy.types.SSSEKAI_OT_export_typetree_op",), ""),
        ("zh_HANS", "导出动画 TypeTree", (False, ())),
    ),
    (
        ("*", "Export the TypeTree of the selected animation"),
        (("bpy.types.SSSEKAI_OT_export_typetree_op",), ""),
        ("zh_HANS", "导出选中动画的 TypeTree", (False, ())),
    ),
    (("*", "Face"), (("",), ""), ("zh_HANS", "面部", (False, ()))),
    (
        ("*", "Import"),
        (("scripts/addons/sssekai_blender_io/blender/addon.py:943",), ""),
        ("zh_HANS", "导入", (False, ())),
    ),
    (
        ("Operator", "Import Armature Animation"),
        (("bpy.types.SSSEKAI_OT_rla_import_armature_animation_op",), ""),
        ("zh_HANS", "导入骨骼动画", (False, ())),
    ),
    (
        ("*", "Import Armature Animation for the selected character"),
        (("bpy.types.SSSEKAI_OT_rla_import_armature_animation_op",), ""),
        ("zh_HANS", "为选中的角色导入骨骼动画", (False, ())),
    ),
    (
        ("Operator", "Import Physics"),
        (("bpy.types.SSSEKAI_OT_import_physics_op",), ""),
        ("zh_HANS", "导入物理", (False, ())),
    ),
    (
        ("*", "Import RLA Pose"),
        ((("scripts/addons/sssekai_blender_io/blender/addon.py:701",),), ""),
        ("zh_HANS", "导入 RLA Pose", (False, ())),
    ),
    (
        (
            "*",
            "Import RLA Pose (armature/shapekey) for the selected object from a JSON, "
            "into the offset frame set in Animation Options. NOTE: The face/body "
            "armature must be pre-processed with the Merge option!",
        ),
        ((("scripts/addons/sssekai_blender_io/blender/addon.py:702",),), ""),
        (
            "zh_HANS",
            "导入单个，JSON格式的 RLA Pose. 考虑动画导入设置的偏移帧数选项；注意：请对你的角色头部/身体事先进行【合并】操作",
            (False, ()),
        ),
    ),
    (
        ("Operator", "Import Selected"),
        (("bpy.types.SSSEKAI_OT_import_op",), ""),
        ("zh_HANS", "导入", (False, ())),
    ),
    (
        ("Operator", "Import Shapekey Animation"),
        (("bpy.types.SSSEKAI_OT_rla_import_shapekey_animation_op",), ""),
        ("zh_HANS", "导入 ShapeKey 动画", (False, ())),
    ),
    (
        ("*", "Import Shapekey Animation for the selected character"),
        (("bpy.types.SSSEKAI_OT_rla_import_shapekey_animation_op",), ""),
        ("zh_HANS", "为选中的角色导入 ShapeKey 动画", (False, ())),
    ),
    (
        (
            "*",
            "Import physics data from the selected asset bundle. NOTE: This operation "
            "is irreversible!",
        ),
        (("bpy.types.SSSEKAI_OT_import_physics_op",), ""),
        ("zh_HANS", "从选中的素材包导入物理数据。注意：此操作不可逆！", (False, ())),
    ),
    (
        ("*", "Import the selected asset from the selected asset bundle"),
        (("bpy.types.SSSEKAI_OT_import_op",), ""),
        ("zh_HANS", "从选中的素材包导入选中的素材", (False, ())),
    ),
    (
        (
            "*",
            "JSON of a single RLA pose (e.g. {'bodyPosition':...}) dumped by rla2json "
            "w/ sssekai",
        ),
        ((("scripts/addons/sssekai_blender_io/blender/addon.py:1050",),), ""),
        (
            "zh_HANS",
            "单个 JSON 格式的 RLA Pose (e.g. {'bodyPosition':...})，可由 rla2json 取得",
            (False, ()),
        ),
    ),
    (
        ("*", "Material Options"),
        (("scripts/addons/sssekai_blender_io/blender/addon.py:922",), ""),
        ("zh_HANS", "材质选项", (False, ())),
    ),
    (
        ("*", "Merge"),
        ((("scripts/addons/sssekai_blender_io/blender/addon.py:310",),), ""),
        ("zh_HANS", "合并", (False, ())),
    ),
    (
        ("Operator", "Merge Armatures"),
        (("bpy.types.SSSEKAI_OT_util_armature_merge_op",), ""),
        ("zh_HANS", "合并骨架", (False, ())),
    ),
    (
        (
            "*",
            "Merge one armature into another, taking constraints & modifed rest poses "
            "into consideration.  With the active one as the newly merged armature.",
        ),
        (("bpy.types.SSSEKAI_OT_util_armature_merge_op",), ""),
        (
            "zh_HANS",
            "将一个骨架合并到另一个骨架中，考虑约束和修改后的初始姿势。以活动骨架作为新合并的骨架。",
            (False, ()),
        ),
    ),
    (
        ("*", "Merge the selected face armature with the selected body armature"),
        (("bpy.types.SSSEKAI_OT_util_neck_merge_op",), ""),
        ("zh_HANS", "将选中的面部骨架与选中的身体骨架合并", (False, ())),
    ),
    (
        ("*", "Misc"),
        ((("scripts/addons/sssekai_blender_io/blender/addon.py:265",),), ""),
        ("zh_HANS", "杂项", (False, ())),
    ),
    (
        ("*", "Number of segments: %d"),
        (("scripts/addons/sssekai_blender_io/blender/addon.py:888",), ""),
        ("zh_HANS", "段数：%d", (False, ())),
    ),
    (
        ("*", "Offset"),
        ((("scripts/addons/sssekai_blender_io/blender/addon.py:1075",),), ""),
        ("zh_HANS", "偏移量", (False, ())),
    ),
    (
        ("*", "Override Unity Version"),
        (("",), ""),
        ("zh_HANS", "手动指定 Unity 版本", (False, ())),
    ),
    (
        ("*", "Project SEKAI Asset Importer for Blender 4.0+"),
        (("Add-on SSSekai Blender IO info: description",), ""),
        (
            "zh_HANS",
            "世界计划缤纷舞台！ feat. 初音未来 游戏素材导入工具 (Blender 4.0+)",
            (False, ()),
        ),
    ),
    (("*", "RLA Bundle"), (("",), ""), ("zh_HANS", "RLA 素材包", (False, ()))),
    (("*", "RLA Clip"), (("",), ""), ("zh_HANS", "RLA 片段", (False, ()))),
    (
        ("*", "RLA Import"),
        (("bpy.types.OBJ_PT_sssekai_rla_import",), ""),
        ("zh_HANS", "RLA 导入", (False, ())),
    ),
    (
        ("*", "RLA Pose JSON"),
        ((("scripts/addons/sssekai_blender_io/blender/addon.py:1049",),), ""),
        ("zh_HANS", "RLA Pose JSON", (False, ())),
    ),
    (
        ("Operator", "Recalculate Hash Table"),
        (("bpy.types.SSSEKAI_OT_util_misc_recalculate_bone_hash_table_op",), ""),
        ("zh_HANS", "重新计算动画哈希表", (False, ())),
    ),
    (
        (
            "*",
            "Recalculate the animation hash table for the selected "
            "armature/articulation. You should do this after renaming bones or changing "
            "the hierarchy.",
        ),
        (("bpy.types.SSSEKAI_OT_util_misc_recalculate_bone_hash_table_op",), ""),
        (
            "zh_HANS",
            "重新计算选中骨架/关节的动画哈希表。在重命名骨骼或更改层次结构后应执行此操作。",
            (False, ()),
        ),
    ),
    (
        ("Operator", "Remove Bone Hierarchy"),
        (("bpy.types.SSSEKAI_OT_util_misc_remove_bone_hierarchy_op",), ""),
        ("zh_HANS", "移除骨架层次结构", (False, ())),
    ),
    (
        ("Operator", "Remove Numeric Suffix"),
        (("bpy.types.SSSEKAI_OT_util_misc_rename_remove_numeric_suffix_op",), ""),
        ("zh_HANS", "移除数字后缀", (False, ())),
    ),
    (
        ("*", "Remove the hierarchy from the selected bones in Edit Mode"),
        (("bpy.types.SSSEKAI_OT_util_misc_remove_bone_hierarchy_op",), ""),
        ("zh_HANS", "在编辑模式下移除选中骨骼的层次结构", (False, ())),
    ),
    (
        (
            "*",
            "Remove the suffix from the selected objects and edit bones (i.e. xxx.001 "
            "-> xxx)",
        ),
        (("bpy.types.SSSEKAI_OT_util_misc_rename_remove_numeric_suffix_op",), ""),
        (
            "zh_HANS",
            "从选中对象和编辑骨骼中移除后缀（例如 xxx.001 -> xxx）",
            (False, ()),
        ),
    ),
    (
        ("*", "SSSekai Blender IO"),
        (("Add-on SSSekai Blender IO info: name",), ""),
        ("zh_HANS", "SSSekai Blender IO", (False, ())),
    ),
    (
        ("Operator", "Search"),
        (("bpy.types.SSSEKAI_OT_asset_search_op",), ""),
        ("zh_HANS", "搜索", (False, ())),
    ),
    (
        ("*", "Search for assets with their object name and/or container name"),
        (("bpy.types.SSSEKAI_OT_asset_search_op",), ""),
        ("zh_HANS", "通过对象名称和/或容器名称搜索素材", (False, ())),
    ),
    (
        ("*", "Select Asset"),
        (("scripts/addons/sssekai_blender_io/blender/addon.py:913",), ""),
        ("zh_HANS", "选择素材", (False, ())),
    ),
    (
        ("*", "Select Targets"),
        (("scripts/addons/sssekai_blender_io/blender/addon.py:354",), ""),
        ("zh_HANS", "选择对象", (False, ())),
    ),
    (("*", "Selected Asset"), (("",), ""), ("zh_HANS", "选中的素材", (False, ()))),
    (
        ("*", "Selected RLA Clip"),
        ((("scripts/addons/sssekai_blender_io/blender/addon.py:1040",),), ""),
        ("zh_HANS", "选中的 RLA 片段", (False, ())),
    ),
    (
        ("*", "Selected RLA Clip "),
        (("",), ""),
        ("zh_HANS", "选中的RLA 片段", (False, ())),
    ),
    (
        ("Operator", "Show Physics Objects"),
        (("bpy.types.SSSEKAI_OT_display_physics_op",), ""),
        ("zh_HANS", "显示物理对象", (False, ())),
    ),
    (
        ("*", "Show or hide physics objects"),
        (("bpy.types.SSSEKAI_OT_display_physics_op",), ""),
        ("zh_HANS", "显示或隐藏物理对象", (False, ())),
    ),
    (
        ("Operator", "Simplify Armature"),
        (("bpy.types.SSSEKAI_OT_util_armature_simplify_op",), ""),
        ("zh_HANS", "简化骨架", (False, ())),
    ),
    (
        (
            "*",
            "Simplify the bone hierachy of the selected armature. This operation is "
            "irreversible!",
        ),
        (("bpy.types.SSSEKAI_OT_util_armature_simplify_op",), ""),
        ("zh_HANS", "简化选中骨架的骨骼层次结构。此操作不可逆！", (False, ())),
    ),
    (
        ("*", "Statistics"),
        (("scripts/addons/sssekai_blender_io/blender/addon.py:880",), ""),
        ("zh_HANS", "统计", (False, ())),
    ),
    (
        ("*", "The bundle file inside 'streaming_live/archive' directory"),
        (("",), ""),
        ("zh_HANS", "位于 'streaming_live/archive' 目录中的素材包文件", (False, ())),
    ),
    (
        (
            "*",
            "The bundle file inside 'streaming_live/archive' directory.\n"
            "Or alternatively, a ZIP file containing 'sekai.rlh' (json) and respective "
            "'sekai_xx_xxxxxx.rla' files. These files should have the extension '.rlh', "
            "'.rla'",
        ),
        ((("scripts/addons/sssekai_blender_io/blender/addon.py:1035",),), ""),
        (
            "zh_HANS",
            "'streaming_live/archive'中的bundle文件\n"
            "或者，一个包含 sekai.rlh, sekai_xx_xxxxxx.rla 的zip文件也同样可用",
            (False, ()),
        ),
    ),
    (
        ("*", "Time %.2fs - %.2fs"),
        (("scripts/addons/sssekai_blender_io/blender/addon.py:884",), ""),
        ("zh_HANS", "时间 %.2fs - %.2fs", (False, ())),
    ),
    (
        (
            "*",
            "Treating armatures as articulations instead of skinned meshes. Useful for "
            "importing stages, etc",
        ),
        (("",), ""),
        ("zh_HANS", "将骨架视为关节而不是蒙皮网格。适用于导入舞台等", (False, ())),
    ),
    (
        ("*", "Unity"),
        ((("scripts/addons/sssekai_blender_io/blender/addon.py:1082",),), ""),
        ("zh_HANS", "Unity", (False, ())),
    ),
    (
        ("*", "Use Principled BSDF"),
        (("",), ""),
        ("zh_HANS", "使用原理化 BSDF", (False, ())),
    ),
    (
        ("*", "Use Principled BSDF instead of SekaiShader for imported materials"),
        (("",), ""),
        ("zh_HANS", "导入材质时使用原理化 BSDF 而不是 SekaiShader", (False, ())),
    ),
    (
        ("*", "Version: %d.%d"),
        (("scripts/addons/sssekai_blender_io/blender/addon.py:882",), ""),
        ("zh_HANS", "版本：%d.%d", (False, ())),
    ),
    (
        (
            "*",
            "Where the asset bundle(s) are located. Every AssetBundle in this directory "
            "will be loaded (if possible)",
        ),
        (("",), ""),
        (
            "zh_HANS",
            "素材包所在的目录。此目录中的每个素材包都将被加载（如果可能）",
            (False, ()),
        ),
    ),
]

translations_dict = {}
for msg in translations_tuple:
    key = msg[0]
    for lang, trans, (is_fuzzy, comments) in msg[2:]:
        if trans and not is_fuzzy:
            translations_dict.setdefault(lang, {})[key] = trans
